//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5448
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Mojo.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class tiledVolumeDescription {
        
        private int numBytesPerVoxelField;
        
        private int numVoxelsPerTileXField;
        
        private int numVoxelsPerTileYField;
        
        private int numVoxelsPerTileZField;
        
        private int numTilesXField;
        
        private int numTilesYField;
        
        private int numTilesZField;
        
        private string fileExtensionField;
        
        private string dxgiFormatField;
        
        private int numTilesWField;
        
        private bool isSignedField;
        
        private int numVoxelsXField;
        
        private int numVoxelsYField;
        
        private int numVoxelsZField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numBytesPerVoxel {
            get {
                return this.numBytesPerVoxelField;
            }
            set {
                this.numBytesPerVoxelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numVoxelsPerTileX {
            get {
                return this.numVoxelsPerTileXField;
            }
            set {
                this.numVoxelsPerTileXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numVoxelsPerTileY {
            get {
                return this.numVoxelsPerTileYField;
            }
            set {
                this.numVoxelsPerTileYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numVoxelsPerTileZ {
            get {
                return this.numVoxelsPerTileZField;
            }
            set {
                this.numVoxelsPerTileZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numTilesX {
            get {
                return this.numTilesXField;
            }
            set {
                this.numTilesXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numTilesY {
            get {
                return this.numTilesYField;
            }
            set {
                this.numTilesYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numTilesZ {
            get {
                return this.numTilesZField;
            }
            set {
                this.numTilesZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fileExtension {
            get {
                return this.fileExtensionField;
            }
            set {
                this.fileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string dxgiFormat {
            get {
                return this.dxgiFormatField;
            }
            set {
                this.dxgiFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numTilesW {
            get {
                return this.numTilesWField;
            }
            set {
                this.numTilesWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSigned {
            get {
                return this.isSignedField;
            }
            set {
                this.isSignedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numVoxelsX {
            get {
                return this.numVoxelsXField;
            }
            set {
                this.numVoxelsXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numVoxelsY {
            get {
                return this.numVoxelsYField;
            }
            set {
                this.numVoxelsYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int numVoxelsZ {
            get {
                return this.numVoxelsZField;
            }
            set {
                this.numVoxelsZField = value;
            }
        }
    }
}
