#pragma once

const int MAX_UNDO_OPERATIONS = 20;
const int FILE_SYSTEM_TILE_CACHE_SIZE = 1024;
const int TILE_SIZE = 512;
const int SPLIT_ADJUST_BUFFER_TILE_HALO = 2;
const int MAX_DEVICE_TILE_CACHE_SIZE = 128;
const int EXTRA_SEGMENTS_PER_SESSION = 1024;
